- name: Create namespace for local-images
  k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Build sample new-app using s2i
  shell: "{{ oc_binary }} -n {{ namespace }} new-app {{ s2i_app_location }}"

- name: Check s2i build is completed
  k8s_facts:
    kind: Build
    api_version: v1
    namespace: "{{ namespace }}"
    label_selectors: "app={{ s2i_app_location|basename }}"
  register: s2i
  until: s2i.resources[0].get("status", {}).get("phase", "") == "Complete"
  retries: 60
  delay: 5

- name: Create route
  shell: "{{ oc_binary }} -n {{ namespace }} expose service {{ s2i_app_location|basename }}"

- name: Obtain registry host
  shell: "{{ oc_binary }} registry info"
  register: registry_info

- set_fact:
    registry_host: "{{ registry_info.stdout }}"

- name: Run tests
  shell: "{{ item }}"
  with_items:
    - "{{ oc_binary }} run test-dc --image={{ registry_host }}/{{ namespace }}/{{ s2i_app_location|basename }}:latest -n {{ namespace }}"
    - "{{ oc_binary }} run test-job --image={{ registry_host }}/{{ namespace}}/{{ s2i_app_location|basename }}:latest -n {{ namespace }} --restart='OnFailure'"
    - "{{ oc_binary }} run test-standalone --image={{ registry_host}}/{{ namespace }}/{{ s2i_app_location|basename }} -n {{ namespace }} --restart='Never'"

# Fix: By default mig-controller sample shell scripts expect to be in the correct project 
- name: Deploy resources using s2i image
  shell: "{{ oc_binary }} project {{ namespace }} && {{ migration_sample_files }}/{{ item|basename }}"
  with_fileglob:
    - "{{ migration_sample_files }}/*.sh"

- name: Check if deployed 
  include: check.yml
