- name: Get cluster version
  block:
  - name: Check cluster version for 4.x
    k8s_facts:
      kind: ClusterVersion
    register: cv
  
  - name: set 4.x version
    set_fact:
       oc_version: "{{ cv.resources[0].status.desired.version | regex_search('^[0-9]\\.[0-9]+')}}"
    when: cv.resources | length > 0

  - debug: msg={{ oc_version }}
    when: cv.resources | length > 0

  - fail:
      msg: "Ocp is not a 4.x cluster"
    when: cv.resources | length == 0

  - name: Set 4.x default registry
    set_fact:
      default_registry: "image-registry.openshift-image-registry.svc:5000"

  rescue:
  - name: Cluster is not 4.x. Checking for 3.x version.
    shell: "{{ oc_binary }} version"
    register: cmdver
  - name: Set  version for 3.x
    set_fact:
      oc_version: "{{ cmdver.stdout | regex_search('openshift v[0-9]\\.[0-9]+') | replace('openshift v', '')  }}"

  - name: Set 3.x default registry
    set_fact:
      default_registry: "docker-registry.default.svc:5000"

  - debug: msg={{ oc_version }}


- name: Set apis
  set_fact:
    cronjob_api: "{{ apis.cronjob.get(oc_version, apis.cronjob.get('default')) }}"
    role_api: "{{ apis.role.get(oc_version, apis.role.get('default')) }}"
    rolebinding_api: "{{ apis.rolebinding.get(oc_version, apis.rolebinding.get('default')) }}"
    deployment_api: "{{ apis.deployment.get(oc_version, apis.deployment.get('default')) }}"
    daemonset_api: "{{ apis.daemonset.get(oc_version, apis.daemonset.get('default')) }}"
    replicaset_api: "{{ apis.replicaset.get(oc_version, apis.replicaset.get('default')) }}"
    statefulset_api: "{{ apis.statefulset.get(oc_version, apis.statefulset.get('default')) }}"
