# Fix for OCP3.7-9
# See : https://github.com/fusor/mig-demo-apps/issues/7
- name: Create namespace for {{ migration_sample_name }}
  shell: "{{ oc_binary }} new-project {{ namespace }} --skip-config-write=true"

- name: Deploy mysql sample
  k8s:
    state : present
    definition: "{{ lookup('template', 'mysql-persistent-template.yml' )}}"

- name: Check if deployed 
  include: check.yml

- name: Load sample data
  include: load_data.yml
