- name: Check mysql status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "app=mysql"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 10
  delay: 15
