---
apiVersion: v1
kind: ProjectRequest
metadata:
  labels:
  name: mediawiki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ src_storage_class | quote }}
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mariadb
  namespace: mediawiki
  labels:
    app: mariadb
    service: mariadb
spec:
  replicas: 1
  selector:
    app: mariadb
    service: mariadb
  strategy:
    type: Rolling
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  test: false
  triggers:
    - type: ConfigChange
  template:
    metadata:
      labels:
        app: mariadb
        service: mariadb
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - image: registry.access.redhat.com/rhscl/mariadb-102-rhel7
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'passwd'
            - name: MYSQL_USER
              value: 'passwd'
            - name: MYSQL_PASSWORD
              value: 'passwd'
            - name: MYSQL_DATABASE
              value: 'passwd'
          terminationMessagePath: /dev/termination-log
          workingDir: /
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql/data
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mediawiki
  labels:
    app: mariadb
    service: mariadb
spec:
  ports:
    - name: port-3306
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mariadb
    service: mariadb
