- name: Check {{ migration_sample_name }} mongodb resource status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "name=mongodb"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 60
  delay: 10

- name: Check {{ migration_sample_name }} restify resource status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "app=restify"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 60
  delay: 10

- name: Obtain {{ migration_sample_name }} route
  k8s_facts:
    kind: Route
    namespace: "{{ namespace }}"
    name: "restify"
  register: parks_app_route

- debug:
    msg: "Will check {{ migration_sample_name }} at http://{{ parks_app_route.resources[0].spec.host }}"

- name: Verify {{ migration_sample_name }} is available
  uri:
    url: "http://{{ parks_app_route.resources[0].spec.host }}"
    method: GET
    return_content: yes
  register: uri
  until: "'Parks' in uri.content"
  retries: 6
  delay: 10
