---
migration_sample_name: nfs-pv
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name}}-mig-{{ ansible_date_time.epoch }}"
migration_sample_files: "{{ playbook_dir }}/roles/{{ migration_sample_name }}/files"
pv: true
pv_action: move
pv_copy_method: filesystem
quiesce: true
stage: false
storage_class: gp2
oc_binary: "oc"
with_deploy: true
with_migrate: true
with_cleanup: true
with_validate: true
namespace: mysql-persistent
